COHERE_API_KEY = "pY0RWQCBSdpAOvDnWaj34UJmlcouxIcagE6ej5uG"

[FIREBASE_KEY]
type = "service_account"
project_id = "vibe-dd050"
private_key_id = "123abc456def..."
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG...
... (no \n, just real line breaks here)
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk@vibe-dd050.iam.gserviceaccount.com"
client_id = "12345678901234567890"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk@vibe-dd050.iam.gserviceaccount.com"
