COHERE_API_KEY = "pY0RWQCBSdpAOvDnWaj34UJmlcouxIcagE6ej5uG"

[FIREBASE_KEY]
type = "service_account"
project_id = "vibe-dd050"
private_key_id = "d3b95fedf59e30df9aa5f581f1e4fdc6767b5f6d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqFC3ycf1SmUV7
cjSax6W2hZh/fJSCbRuDkHUvNQ81kikSLRzZRjun7aL3J4Ohl6RMtMk0nu11smoG
gLieyA0Tl1RcS5/mSUwSx06gpn8VCVbGFCxs081D0okvHGzruBe/1ufoVU8inbIY
jP9vBGEcNcOCLS+9NdavuJla6FJTueWSW9U+BBZEColuszypp41I+XJ6z831miII
EtU2u0eNceU2tK2UhukZN8egLRoGBnbqA2dmUmH0pXmm2G7sMDJnJw/fWmB6uveo
ikXm2dHcg0n+0EPwo3B5bRGPH1W37NxB9SdeynvoJ4SVTYN2EK0LDM4vZCnefTWp
LMURkNatAgMBAAECggEAAIncZIf4z7Dyh4y1swXypA1fhBTvBWiWypfJn1km92Od
X4KSviKZMVTvtYWTEpPFxrYkKfPZzCFM2bwbET99cnFjC9r9L3JqgOe30QZ/HnVi
9DziDxcUoT0mwrIfDvIfZaWO+BHr0iQi7M709qYbwxbDC+1L3fvFpd6VvFCSpjvv
SSDJA7gSU1+dFnVqlWRdLHUpvPp9lzeU/Gfi6j3HpYB/6PUnU9+tJ6Tbc/WYGN//
pexMQBx0uMtEZeIDgzVC9TnThQwDYxPnQ51TAHYSpZUc2tuL8gCoKhaGQLxCXvoJ
iZ8mMQIQtx60rJYmbJ6Tfc4uqtbLw05CRVrYVSwC+QKBgQDY8fp1STy5OkiIKkzx
6YbUAdCAcGTVP7TuLW6d4LND659YKGJwDgFm7kHc9+jWWrND8W8rw8HRao2Def3G
6e1SzxDlbVUtzj0ApyxzujFBNTby3wN/S0Z1llfN7ec2zyRnzvPs7CgbLamh0aQE
QmtCosBDdw/NwegQo80hK3939QKBgQDIsldaMZpEfUja7Cnhh7S9ywW/5AF5oAkp
rgs1qMRtA+/Pn+Kygi/wJCkTIGx+rDNbjPYejNiqr8eyC9v8GAPdfw/64HCQWwIG
0MFvJpeYJkl1gvsxvjgYS8r4q+4vjAn4hQc9J7yu+cfrs7clOMk0P7FtyD3Gx461
2Xga82KI2QKBgHWElwTjuFYqQVIpf+bndpbvqK96stRlnzAKQkqZhuI7B+Uscy56
F75XQCxfyqwbE9KxPWR6tUooqyHWemc/HsTl0CRH1oVqm9b3t/e0m6vUFMD5l55j
+3YFC+lMfxxMl074Z2AnCQ637JTwyCVaiVneacHiBBiUeo5Q/PSD6JflAoGAO0ir
EwJ5/mc/wSNnz64FjtbM8P0KDoJekohN2WDr/QPfr+Yb0f0w6e/UjkjSo6x8UzvV
a/rQ+cKI66gjKFlzstcYwlPQDGRFufuqWAn/V7tfka3KQ8xbx5mD8GbhKfxk6Ztq
Iv989fbkvlRM8lrO3HdAExzGWtSR7Fe76cIhRikCgYEAq52qWxFsmaNWZf/8D0SF
C6gWBKHSx8nlcUNEZSFR7PTgQaZFTeD8uEDQFHPymlGZKwcpMmEVkA5P8f6in8Jc
lOZLLv1PN78o83avtE/RJcVkLq8Y2vXNxjljQ5s6SjMm0o78mrYmhFyEBd18F7Ez
PS3/HL0A92Wl1/pPgI89iYE=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@vibe-dd050.iam.gserviceaccount.com"
client_id = "110300436916851255782"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@vibe-dd050.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

